FROM ubuntu:22.04

ENV MAKEFLAGS="-j 8"


RUN apt-get update \
    && apt-get install -y --no-install-recommends python3-pip build-essential python3-dev \
    && pip3 install requests pydantic 'https://github.com/theblazehen/yt-dlp/archive/refs/heads/master.zip#egg=yt-dlp'

COPY . /app
WORKDIR /app

CMD ["/usr/bin/python3", "-u", "process_video_work.py"]