FROM ubuntu:22.04

ENV MAKEFLAGS="-j 8"


RUN apt-get update \
    && apt-get install -y --no-install-recommends python3-pip build-essential python3-dev curl \
    && pip3 install requests beautifulsoup4

COPY . /app
WORKDIR /app

CMD ["/usr/bin/python3", "-u", "process_user_work.py"]